spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/red_comunitaria_talentotech15
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

server:
  port: 8080
  error:
    include-message: always